USE EMPLOYEE_DB;

INSERT INTO DEPARTMENT(NAME) VALUES ('Corporate');
INSERT INTO DEPARTMENT(NAME) VALUES ('Management');
INSERT INTO DEPARTMENT(NAME) VALUES ('Sales');
INSERT INTO DEPARTMENT(NAME) VALUES ('Accounting');
INSERT INTO DEPARTMENT(NAME) VALUES ('Quality Assurance');
INSERT INTO DEPARTMENT(NAME) VALUES ('Customer Support');

INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Wunderkid', 80000, 1);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Regional Manager', 60000, 2);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Co-Manager', 60000, 2);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Assistant to the Regional Manager', 50000, 3);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Regional Director in Charge of Sales', 50000, 3);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Head of Accounting', 50000, 4);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Accountant', 50000, 4);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Head of Quality Assurance', 50000, 5);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Customer Service Representative', 40000, 6);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Sales Representative', 40000, 3);
INSERT INTO ROLE (TITLE, SALARY, DEPARTMENT_ID)
VALUES ('Human Resources', 40000, 1);

INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID)
VALUES ('Ryan', 'Howard', 1);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Michael', 'Scarn', 2, 1);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Jim', 'Halpert', 3, 2);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Dwight', 'Schrute', 4, 3);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Andy', 'Bernard', 5, 3);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Angela', 'Martin', 6, 2);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Oscar', 'Martinez', 7, 6);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Kevin', 'Malone', 7, 6);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Creed', 'Bratton', 8, 2);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Phyllis', 'Lapin', 10, 3);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Stanley', 'Hudson', 10, 3);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Kelly', 'Kapoor', 9, 2);
INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, ROLE_ID, MANAGER_ID)
VALUES ('Toby', 'Flenderson', 11, 2);